name: Percy Snapshots

on:
  push:
  pull_request:

jobs:
  nonce:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.nonce.outputs.result }}
    steps:
    - id: nonce
      run: echo "::set-output name=result::${{ github.run_id }}-$(date +%s)"

  default-snapshots:
    needs: nonce
    uses: yext/answers-headless/.github/workflows/percy_snapshots_reuse.yml@dev/test-reusable-workflows
    with:
      build_script: npm run setup-test-site && npm run build-test-site
      # snapshots_script_path: tests/percy/index.js
      percy_script: npx percy exec --parallel -- node tests/percy/index.js
    secrets:
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      PERCY_PARALLEL_NONCE: ${{ needs.nonce.outputs.result }}
      PERCY_PARALLEL_TOTAL: 4

    # runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [12.18]
    # steps:
    #   - uses: actions/checkout@v2
    #   - name: Use Node.js ${{ matrix.node-version }}
    #     uses: actions/setup-node@v1
    #     with:
    #       node-version: ${{ matrix.node-version }}
    #   - run: npm ci
    #   - run: npm run setup-test-site
    #   - run: npm run build-test-site
    #   - name: Percy snapshots
    #     run: npx percy exec --parallel -- node tests/percy/index.js
    #     env:
    #       PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    #       PERCY_PARALLEL_NONCE: ${{ needs.nonce.outputs.result }}
    #       PERCY_PARALLEL_TOTAL: 4

  iframe-snapshots:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.18]
    needs: nonce
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run setup-test-site
      - run: npm run build-test-site
      - name: Percy snapshots
        run: npx percy exec --parallel -- node tests/percy/index.js iframe
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_PARALLEL_NONCE: ${{ needs.nonce.outputs.result }}
          PERCY_PARALLEL_TOTAL: 4

  spanish-snapshots:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.18]
    needs: nonce
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run setup-test-site
      - run: npm run build-test-site
      - name: Percy snapshots
        run: npx percy exec --parallel -- node tests/percy/index.js spanish
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_PARALLEL_NONCE: ${{ needs.nonce.outputs.result }}
          PERCY_PARALLEL_TOTAL: 4

  rtl-snapshots:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.18]
    needs: nonce
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run setup-test-site
      - run: npm run build-test-site
      - name: Percy snapshots
        run: npx percy exec --parallel -- node tests/percy/index.js rtl
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_PARALLEL_NONCE: ${{ needs.nonce.outputs.result }}
          PERCY_PARALLEL_TOTAL: 4
